refactor: update pr-labeler

diff --git a/.github/workflows/pr-labeler.yml b/.github/workflows/pr-labeler.yml
--- a/.github/workflows/pr-labeler.yml
+++ b/.github/workflows/pr-labeler.yml
@@ -65,18 +65,17 @@ jobs:
         # Verified creator: https://github.com/marketplace/actions/checkout
         # GitHub Action for checking out a repo
         uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
-        #uses: actions/checkout@v4.1.3
 
       - name: Forked repo | Exit workflow early in forked repo
         id: check-repo-owner
         if: (github.repository_owner != 'rwaight')
         run: |
           echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
-          echo "  if the workflow actually runs, then the 'exit 0' below will need to be changed to a non-zero. "
+          ##echo "  if the workflow actually runs, then the 'exit 0' below will need to be changed to a non-zero. "
           gh run cancel ${{ github.run_id }}
           echo "The 'check-repo-owner' step is finishing and this workflow will now exit. "
           gh run watch ${{ github.run_id }}
-          exit 0
+          exit 1
         # might need to include `gh run watch ${{ github.run_id }}` if 'gh run cancel' does not exit the workflow
         env:
           GH_TOKEN: ${{ github.token }}
@@ -107,7 +106,7 @@ jobs:
           echo ""
           echo "The 'check-for-any-labels' step has completed. "
 
-      - name: Autorelease | Set the label scope to 'version'
+      - name: Autorelease | Set the label scope to 'version' for semver checking
         #name: Autorelease | Check 'autorelease' branch
         id: set-label-scope-semver
         #if: contains('refs/heads/autorelease', github.ref)
@@ -142,6 +141,49 @@ jobs:
             echo "::error::Version '$VERSION' is not in a valid format" && exit 1
           fi
           echo "The 'set-label-scope-semver' step has completed. "
+
+      - name: Autorelease | parse the branch name
+        id: autorelease-parse-branch-name
+        if: startsWith(github.event.pull_request.head.ref, 'autorelease')
+        run: |
+          echo "starting the 'autorelease-parse-branch-name' step. "
+          echo "this means that 'github.event.pull_request.head.ref' starts with 'autorelease' (single quotes) "
+          echo ""
+          echo "event pr head ref:  ${{ github.event.pull_request.head.ref }}"
+          HEAD_REF="${{ github.event.pull_request.head.ref }}"
+          ##  
+          RE_AUTO='^(autorelease)\/([vV]?(([0-9]+)[.]([0-9]+)[.]([0-9]+)(-[0-9A-Za-z.+-]*)?))'
+          if [[ $HEAD_REF =~ $RE_AUTO ]]; then
+              AUTO_NAME="${BASH_REMATCH[1]}"
+              FULL_VER="${BASH_REMATCH[2]}"
+              VER_NO_V="${BASH_REMATCH[3]}"
+              MAJOR="${BASH_REMATCH[4]}"
+              MINOR="${BASH_REMATCH[5]}"
+              PATCH="${BASH_REMATCH[6]}"
+              PRERELEASE="${BASH_REMATCH[7]}"
+              ##
+              if [ 'true' == 'true' ]; then
+                  echo "HEAD_REF is: $HEAD_REF "
+                  echo "RE_AUTO is : $RE_AUTO "
+                  echo ""
+                  echo "AUTO_NAME is: $AUTO_NAME "
+                  echo "FULL_VER is : $FULL_VER "
+                  echo "VER_NO_V is : $VER_NO_V "
+                  echo ""
+                  echo "MAJOR is  : $MAJOR "
+                  echo "MINOR is  : $MINOR "
+                  echo "PATCH is  : $PATCH "
+                  echo "PRERELEASE: $PRERELEASE"
+              fi
+              ##
+              echo "next thing to do is to output whichever match group, so it can be tested... "
+          else
+              echo "the head ref did not match the regex, but the branch name starts with 'autorelease'."
+              ## use the warning below once the 'autorelease' startsWith conditionals are working
+              echo "::warning file=pr-labeler,title=autorelease-parse-branch-name::the head ref did not match the regex, but the branch name starts with 'autorelease'."
+          fi
+          ##
+          echo "completing the 'autorelease-parse-branch-name' step. "
 
       - name: Set the label scope to 'type'
         id: set-label-scope-type
@@ -184,11 +226,10 @@ jobs:
         # Verified creator: https://github.com/marketplace/actions/create-github-app-token
         # GitHub Action for creating a GitHub App installation access token.
         uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
-        #uses: actions/create-github-app-token@v1.10.0
         id: app-token
         # Skip running on forks or Dependabot since neither has access to secrets
         if: |
-          (github.repository == 'rwaight/test-actions') &&
+          (github.repository_owner == 'rwaight') &&
           (github.actor!= 'dependabot[bot]') &&
           (contains(github.head_ref, 'dependabot-') == false)
         with:
@@ -202,7 +243,6 @@ jobs:
         # Verified creator: https://github.com/marketplace/actions/checkout
         # GitHub Action for checking out a repo
         uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
-        #uses: actions/checkout@v4.1.3
         id: checkout
         # Skip running on forks or Dependabot since neither has access to secrets
         if: steps.app-token.outcome != 'skipped'
@@ -224,11 +264,10 @@ jobs:
         # Verified creator: https://github.com/marketplace/actions/checkout
         # GitHub Action for checking out a repo
         uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
-        #uses: actions/checkout@v4.1.3
         id: checkout-dependabot
         # Run for Dependabot with the default token
         if: |
-          (github.repository == 'rwaight/test-actions') &&
+          (github.repository_owner == 'rwaight') &&
           (github.actor== 'dependabot[bot]') &&
           (contains(github.head_ref, 'dependabot-') == true)
         with:
@@ -248,15 +287,12 @@ jobs:
         # Verified creator: https://github.com/marketplace/actions/labeler
         # An action for automatically labelling pull requests
         uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
-        #uses: actions/labeler@v5.0.0
         id: label-pull-request
         with:
           repo-token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
 
       - name: Autorelease | Check for semantic version labels
-        uses: rwaight/actions/test/check-semver-labels@050473414fe65f13fc4adbaf3c900410c50b9f8a # v0.1.26
-        #uses: rwaight/actions/test/check-semver-labels@v0.1.26
-        #uses: rwaight/actions/test/check-semver-labels@main
+        uses: rwaight/actions/test/check-semver-labels@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
         id: check-semver-labels
         #if: contains(github.event.pull_request.labels.*.name, 'actions:autorelease')
         # this does not work #if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
@@ -270,9 +306,7 @@ jobs:
           my_action_debug: true
 
       - name: Check for type labels
-        uses: rwaight/actions/github/label-checker@050473414fe65f13fc4adbaf3c900410c50b9f8a # v0.1.26
-        #uses: rwaight/actions/github/label-checker@v0.1.26
-        #uses: rwaight/actions/github/label-checker@main
+        uses: rwaight/actions/github/label-checker@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
         id: check-type-labels
         # this does not work #if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
         if: ${{ ! startsWith(github.event.pull_request.head.ref, 'autorelease') }}
@@ -347,9 +381,7 @@ jobs:
 
       # look for a comment 
       - name: Find Comment
-        uses: rwaight/actions/chatops/find-comment@050473414fe65f13fc4adbaf3c900410c50b9f8a # v0.1.26
-        #uses: rwaight/actions/chatops/find-comment@v0.1.26
-        #uses: rwaight/actions/chatops/find-comment@main
+        uses: rwaight/actions/chatops/find-comment@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
         id: find-comment
         if: steps.write-results.outcome != 'skipped'
         #continue-on-error: true
@@ -362,9 +394,7 @@ jobs:
       - name: Generate comment template
         # need to use the 'label_check' outputs ('success' or 'failure' maybe?) to determine which file to use
         id: comment-template
-        uses: rwaight/actions/utilities/render-template@050473414fe65f13fc4adbaf3c900410c50b9f8a # v0.1.26
-        #uses: rwaight/actions/utilities/render-template@v0.1.26
-        #uses: rwaight/actions/utilities/render-template@main
+        uses: rwaight/actions/utilities/render-template@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
         if: steps.write-results.outcome != 'skipped'
         with:
           #idea #template: assets/pr-labeler/comment-checks-${{ steps.check-type-labels.outputs.label_check }}.md
@@ -381,9 +411,7 @@ jobs:
 
       - name: Create or update comment
         id: comment-on-pr
-        uses: rwaight/actions/chatops/create-or-update-comment@050473414fe65f13fc4adbaf3c900410c50b9f8a # v0.1.26
-        #uses: rwaight/actions/chatops/create-or-update-comment@v0.1.26
-        #uses: rwaight/actions/chatops/create-or-update-comment@main
+        uses: rwaight/actions/chatops/create-or-update-comment@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
         if: steps.comment-template.outcome != 'skipped'
         with:
           body: ${{ steps.comment-template.outputs.result }}
