ci(assets): infra updates from SHA a946ad9 (#118)

diff --git a/.github/workflows/pr-labeler.yml b/.github/workflows/pr-labeler.yml
--- a/.github/workflows/pr-labeler.yml
+++ b/.github/workflows/pr-labeler.yml
@@ -1,4 +1,6 @@
 # This workflow currently runs the 'pr-labeler' action
+# This file is sourced from the 'infra' repo, the file location is: 'infra/assets/gh_workflows/pr-labeler.yml'
+
 name: PR Labeler
 run-name: Label PR ${{ github.event.number }} on ${{ github.head_ref || github.ref_name }}
 on:
@@ -14,11 +16,18 @@ on:
       - review_requested
   # workflow_dispatch:
   #   inputs:
-  #     debug_output:
-  #       description: 'Debug output'
+  #     verbose_output:
+  #       description: 'Verbose output'
   #       required: true
   #       default: false
   #       type: boolean
+
+env:
+  VERBOSE_WORKFLOW: ${{ inputs.verbose_output || 'true' }}
+  # the bot name without the '[bot]' suffix
+  GH_LOCAL_BOT_NAME: 'rw-actions-bot'
+  # the owner of the repo, used in conditionals below
+  GH_OWNER: rwaight
 
 # https://docs.github.com/en/actions/using-jobs/using-concurrency
 concurrency:
@@ -31,9 +40,6 @@ concurrency:
 
 jobs:
   pr-labeler:
-    #name: PR Labeler
-    # commenting out the name with the '${{ github.event.number }}' as the job could
-    # not be selected as a required status check as part of protecting branches
     #name: Label pull request ${{ github.event.number }}
     runs-on: ubuntu-latest
     # the 'if' statement below is not needed at this time, but would be if the 'on' section above changes
@@ -54,31 +60,16 @@ jobs:
     #   group: ${{ github.workflow }}-${{ github.ref }}
     #   cancel-in-progress: true
     steps:
-      # Issuing 'exit 0' does not force the workflow to exit early
-      #   need to issue 'gh run cancel ${{ github.run_id }}'
-      #   and might need to change 'exit 0' to 'exit 1' or a non-zero numerical value
-      # https://github.com/orgs/community/discussions/82744#discussioncomment-8718646
-      - name: Forked repo | checkout using built-in token
-        if: (github.repository_owner != 'rwaight')
-        # Save this in case we want to exit the workflow if it is called by 'rw-actions-bot[bot]'
-        #if: (github.repository_owner != 'rwaight') || ${{ github.actor == 'rw-actions-bot[bot]' }}
-        # Verified creator: https://github.com/marketplace/actions/checkout
-        # GitHub Action for checking out a repo
-        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
 
-      - name: Forked repo | Exit workflow early in forked repo
+      - name: Exit workflow in forked repo
         id: check-repo-owner
-        if: (github.repository_owner != 'rwaight')
+        if: ${{ github.repository_owner != env.GH_OWNER }}
+        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
         run: |
           echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
-          ##echo "  if the workflow actually runs, then the 'exit 0' below will need to be changed to a non-zero. "
-          gh run cancel ${{ github.run_id }}
-          echo "The 'check-repo-owner' step is finishing and this workflow will now exit. "
-          gh run watch ${{ github.run_id }}
+          echo "This workflow will now fail and exit. "
+          echo "::error title=⛔ error in the '${{ github.workflow }}' workflow hint::This workflow was run in a forked repo"
           exit 1
-        # might need to include `gh run watch ${{ github.run_id }}` if 'gh run cancel' does not exit the workflow
-        env:
-          GH_TOKEN: ${{ github.token }}
 
       # # Save this in case we want to exit the workflow if it is called by 'rw-actions-bot[bot]'
       # - name: Exit workflow if called by 'rw-actions-bot[bot]'
@@ -90,6 +81,7 @@ jobs:
       #     gh run cancel ${{ github.run_id }}
       #     echo "The 'check-actions-bot' step is finishing and this workflow will now exit. "
       #     gh run watch ${{ github.run_id }}
+      #     exit 1
       #     exit 0
       #   # might need to include `gh run watch ${{ github.run_id }}` if 'gh run cancel' does not exit the workflow
       #   env:
@@ -109,14 +101,8 @@ jobs:
       - name: Autorelease | Set the label scope to 'version' for semver checking
         #name: Autorelease | Check 'autorelease' branch
         id: set-label-scope-semver
-        #if: contains('refs/heads/autorelease', github.ref)
-        # this does not work #if: ${{ contains('refs/heads/autorelease', github.ref) }}
+        # use startsWith instead of contains ##if: ${{ contains('refs/heads/autorelease', github.ref) }}
         if: startsWith(github.event.pull_request.head.ref, 'autorelease')
-        # if: | 
-        #   contains('
-        #     refs/heads/autorelease
-        #     refs/heads/production
-        #   ', github.ref)
         run: |
           ## the double number signs below are for line spacing and readability only
           ##
@@ -187,7 +173,7 @@ jobs:
 
       - name: Set the label scope to 'type'
         id: set-label-scope-type
-        # this does not work #if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
+        # use startsWith instead of contains ##if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
         if: ${{ ! startsWith(github.event.pull_request.head.ref, 'autorelease') }}
         run: |
           ## the double number signs below are for line spacing and readability only
@@ -225,13 +211,12 @@ jobs:
       - name: Create an App Token
         # Verified creator: https://github.com/marketplace/actions/create-github-app-token
         # GitHub Action for creating a GitHub App installation access token.
-        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
+        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
         id: app-token
         # Skip running on forks or Dependabot since neither has access to secrets
         if: |
-          (github.repository_owner == 'rwaight') &&
-          (github.actor!= 'dependabot[bot]') &&
-          (contains(github.head_ref, 'dependabot-') == false)
+          (github.actor != 'dependabot[bot]' &&
+          startsWith(github.event.pull_request.head.ref, 'dependabot') == false)
         with:
           # required
           app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
@@ -242,7 +227,7 @@ jobs:
       - name: Checkout files from commit tree
         # Verified creator: https://github.com/marketplace/actions/checkout
         # GitHub Action for checking out a repo
-        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
+        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
         id: checkout
         # Skip running on forks or Dependabot since neither has access to secrets
         if: steps.app-token.outcome != 'skipped'
@@ -263,13 +248,12 @@ jobs:
       - name: Checkout files from commit tree for dependabot
         # Verified creator: https://github.com/marketplace/actions/checkout
         # GitHub Action for checking out a repo
-        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
+        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
         id: checkout-dependabot
         # Run for Dependabot with the default token
         if: |
-          (github.repository_owner == 'rwaight') &&
-          (github.actor== 'dependabot[bot]') &&
-          (contains(github.head_ref, 'dependabot-') == true)
+          (github.actor == 'dependabot[bot]' &&
+          startsWith(github.event.pull_request.head.ref, 'dependabot') == true)
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -292,10 +276,9 @@ jobs:
           repo-token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
 
       - name: Autorelease | Check for semantic version labels
-        uses: rwaight/actions/test/check-semver-labels@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
+        uses: rwaight/actions/test/check-semver-labels@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
         id: check-version-labels
-        #if: contains(github.event.pull_request.labels.*.name, 'actions:autorelease')
-        # this does not work #if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
+        # use startsWith instead of contains ##if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
         if: startsWith(github.event.pull_request.head.ref, 'autorelease')
         with:
           gh-token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
@@ -306,9 +289,9 @@ jobs:
           my_action_debug: true
 
       - name: Check for type labels
-        uses: rwaight/actions/github/label-checker@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
+        uses: rwaight/actions/github/label-checker@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
         id: check-type-labels
-        # this does not work #if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
+        # use startsWith instead of contains ##if: ${{ ! contains('refs/heads/autorelease', github.ref) }}
         if: ${{ ! startsWith(github.event.pull_request.head.ref, 'autorelease') }}
         with:
           allow_failure: true
@@ -381,7 +364,7 @@ jobs:
 
       # look for a comment 
       - name: Find Comment
-        uses: rwaight/actions/chatops/find-comment@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
+        uses: rwaight/actions/chatops/find-comment@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
         id: find-comment
         if: steps.write-results.outcome != 'skipped'
         #continue-on-error: true
@@ -394,7 +377,7 @@ jobs:
       - name: Generate comment template
         # need to use the 'label_check' outputs ('success' or 'failure' maybe?) to determine which file to use
         id: comment-template
-        uses: rwaight/actions/utilities/render-template@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
+        uses: rwaight/actions/utilities/render-template@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
         if: steps.write-results.outcome != 'skipped'
         with:
           #idea #template: assets/pr-labeler/comment-checks-${{ steps.check-type-labels.outputs.label_check }}.md
@@ -411,14 +394,14 @@ jobs:
 
       - name: Create or update comment
         id: comment-on-pr
-        uses: rwaight/actions/chatops/create-or-update-comment@bd2234d2665c0db7fff5b9b65e904bf58b63bd11 # v0.1.31
+        uses: rwaight/actions/chatops/create-or-update-comment@bb107b0a8f994fbf7d0be216086319b6a468a1da # v0.1.39
         if: steps.comment-template.outcome != 'skipped'
         with:
           body: ${{ steps.comment-template.outputs.result }}
           comment-id: ${{ steps.find-comment.outputs.comment-id }}
           edit-mode: replace
           issue-number: ${{ github.event.number }}
-          token: ${{ steps.app-token.outputs.token }}
+          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
 
       - name: Output comment ID
         if: steps.comment-on-pr.outcome != 'skipped'
